# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('google_id', models.CharField(default='', max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('photo_url', models.CharField(default='', max_length=400)),
                ('serverAuthCode', models.CharField(default='', max_length=400)),
                ('refreshToken', models.CharField(default='', max_length=400)),
                ('idToken', models.CharField(default='', max_length=400)),
                ('accessToken', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
