# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetTutore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='hash_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
