# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetTutore', '0002_members_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='accessToken',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='members',
            name='idToken',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='members',
            name='refreshToken',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='members',
            name='serverAuthCode',
            field=models.TextField(default=''),
        ),
    ]
