# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetTutore', '0003_auto_20180212_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_visitor',
            field=models.IntegerField(default=1),
        ),
    ]
